version: '3.3'

volumes:
  data:

services:
  design-patterns:
    container_name: design-patterns
    volumes:
      - "./:/var/www"
    build: .
    command: [ "php", "-S", "0.0.0.0:8080" ]
    ports:
      - "80:8080"